version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: sgt
    main: ./cmd/sgt/
    binary: sgt
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: sgt
    builds:
      - sgt
    name_template: "sgt-{{ .Os }}-{{ .Arch }}"
    format: binary

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: callmeradical
    name: sgt
  name_template: "{{.Tag}}"
  draft: false

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
